### ISSUE TITLE
[Backend] As a user, I can view my uploaded keywords

### ISSUE THREAD

**Issue by blyscuit** [nimblehq/ic-rails-phong-bliss#11]
## Why

User should be able to see their uploaded keyword.

## Acceptance Criteria

- Modify endpoint from #12 to show uploaded keywords uploaded by the user calling the endpoint.

**Comment by malparty** [comment]
What do we mean by "new function"? Should it be "new endpoint"?

**Comment by blyscuit** [comment]
@malparty I breakdown stories with API to a pair, the API side with endpoints and Backend side with the logic (database integration, data mapping, etc). I will modify the Backend stories to mention the API so that the Backend stories make more sense. 🙏

**Comment by phongvhd93** [comment]
@blyscuit, what do you think if I create a search result model like this? We can add 1 more filed for the search engine (Google or Bing)
![Screenshot 2023-06-01 at 11 26 10](https://github.com/nimblehq/ic-rails-phong-bliss/assets/22606906/a76f8057-57db-472b-84ef-cfb152a0d137)
