### ISSUE TITLE
[Backend] As a user, I can upload a list of keywords to trigger a Google search

### ISSUE THREAD

**Issue by blyscuit** [nimblehq/ic-rails-phong-bliss#15]
## Why

The system should automatically crawl Google for the following data.

- For each search result/keyword result page on Google, you will store in the database the following information on the first page of results:
    - Number of AdWords advertisers in the top position.
    - Total number of AdWords advertisers on the page.
    - URLs of the AdWords advertisers in the top position.
    - Number of the non-AdWords results on the page.
    - URLs of the non-AdWords results on the page.
    - Total number of links (all of them) on the page
    - HTML code of the page/cache of the page.

## Acceptance Criteria

- Add backend function for accessing Google search page with the Keywords
- This function should be called when user is uploading a CSV file.

**Comment by malparty** [comment]
We might need to ask help from a PM for this one ^^ But `As a user` is not relevant in the current title of this story. 

My recommendations would be:
- Either keeping `as a user`, with something like:
  - As a user, I can upload a list of keywords to trigger a Google search
  - As a user, I can search Google when I upload a list of keywords
- Either using another "user". In our current client project, the PM refers to automation with `As the system`: 
  - As the system, I search every uploaded keywords in Google
  - As the system, when a keyword is uploaded, I search it in Google



Similar suggestion for the other stories using `automatically` ;-)
