### ISSUE TITLE
[Backend] As a user, I can access my keyword details

### ISSUE THREAD

**Issue by blyscuit** [nimblehq/ic-rails-phong-bliss#18]
## Why

The user should be able to access their uploaded keyword’s detail.

- The detail of the keyword should include:
    - Number of AdWords advertisers in the top position.
    - Total number of AdWords advertisers on the page.
    - URLs of the AdWords advertisers in the top position.
    - Number of the non-AdWords results on the page.
    - URLs of the non-AdWords results on the page.
    - Total number of links (all of them) on the page
    - HTML code of the page/cache of the page.

## Acceptance Criteria

- Modify endpoint from #19 to fetching a single keyword and map the data as a JSON result.
- Keywords should belong to the user, returns error if user does not have permission to certain keyword.

**Comment by malparty** [comment]
Do we plan to add security (i.e. I cannot access the keywords of another user)? 

If yes: Let's add it in the AC of this story (or create a dedicated story `As a user, I cannot access the keywords details of another user`)

If no: Let's rename this story with "As a user, I can access *a* keyword details"

**Comment by blyscuit** [comment]
@malparty Thank you. I added the extra AC. 🙏
