### ISSUE TITLE
[Chore] Remove frontend capabilities

### ISSUE THREAD

**Issue by blyscuit** [nimblehq/ic-rails-phong-bliss#29]
## Why

This project is backend, using only API to serve content. We can remove anything related to web frontend.

## Acceptance Criteria 

- Remove `yarn`.
- Remove any `HTML`.
- Remove integration test.

**Comment by malparty** [comment]
Related to my suggestion in PR #27 we might not need this Chore if you use the `--api` version of the template 🚀

**Comment by blyscuit** [comment]
Closed by using API version of the template.
