### ISSUE TITLE
[API] As a user, I can access some JSON data

### ISSUE THREAD

**Issue by blyscuit** [nimblehq/ic-rails-phong-bliss#4]
## Why

Set up JSON endpoint for the APIs

## Acceptance Criteria

- Create new API module
- Create endpoint `GET` `/keywords`
    - Endpoint returns JSON with `JSONAPI`
```
[
		{
			"id": "1",
			"type": "keyword",
			"attributes": {
				"name": "First keyword"
			}
		},
		{
			"id": "1",
			"type": "keyword",
			"attributes": {
				"name": "Second keyword"
			}
		}
	]
```

**Comment by malparty** [comment]
Should we rename this story with "As the system or user, I can check the application's health". 

It can be useful to have an `end_point` that returns a small ACK to allow your load balancer to redeploy (or switch the traffic to another instance) in case this route is down.
Example: https://dev-onwardpayroll.com/health_check 

This `health_check` route would allow you to create your first endpoint and return JSON. ;-) But at least it has a utility in the project and you won't need to remove it later 🚀
