### ISSUE TITLE
[Backend] Set up Authentication

### ISSUE THREAD

**Issue by blyscuit** [nimblehq/ic-rails-phong-bliss#5]
## Why

Set up authentication with `Devise` to accommodate `oauth` feature.

## Acceptance Criteria

- Use `Devise`, create endpoint with authentication locked and non-locked.
    - `GET` `/private_items` is authentication locked
    - `POST` `/public_items` is non-locked.
- Create a Chore task to remove the test endpoints.

**Comment by malparty** [comment]
Should we directly use the endpoint of a future story like #11 (private) and signin (public) so that you won't need an additional chore to remove that endpoint 😇
